### ISSUE TITLE
converte utils  to class to and set with own cmake to compile

### ISSUE THREAD

**Issue by Ticafblanc** [Ticafblanc/webserv#63]
build Utils.class.cpp

**Comment by xApologize** [comment]
Done converting converter to class.

**Comment by xApologize** [comment]
converting fileSystem into a class

**Comment by xApologize** [comment]
need to look into the vector of char *

**Comment by xApologize** [comment]
vector of char * works on my laptop but not the school computer? also not sure where to put launchChild and autoIndexHtml

otherwise, transforming the utils in classes is done

**Comment by xApologize** [comment]
include of vector was missing in the setter class... im dumb

**Comment by xApologize** [comment]
auto index: creer une index (directory tree) dans une page html
